name: Build Libation image

on:
  pull_request:
    paths:
      - images/libation/**
      - .github/workflows/libation-build.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository_owner}}/toolbox-libation

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        fedora_version: ["42", "43"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get latest Libation version
        id: libation_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/rmcrackan/Libation/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "Latest Libation version: $LATEST_VERSION"

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=fedora-${{matrix.fedora_version}}-libation-${{steps.libation_version.outputs.version}}
            type=raw,value=fedora-${{matrix.fedora_version}}-latest

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.12
        with:
          context: images/libation
          containerfiles: |
            images/libation/Containerfile
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FEDORA_VERSION=${{matrix.fedora_version}}
            LIBATION_VERSION=${{steps.libation_version.outputs.version}}
          oci: true
